DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
   ID SERIAL PRIMARY KEY,
   NAME TEXT NOT NULL,
   BIRTHDAY DATE
);

INSERT INTO USERS (NAME,BIRTHDAY)
VALUES ('Paul', '1982-08-05');

INSERT INTO USERS (NAME,BIRTHDAY)
VALUES ('Allen', '1976-02-29');

INSERT INTO USERS (NAME,BIRTHDAY)
VALUES ('Teddy', '1980-06-10');

INSERT INTO USERS (NAME,BIRTHDAY)
VALUES ('Mark', '1992-06-13');

INSERT INTO USERS (NAME,BIRTHDAY)
VALUES ('James', '1987-07-08');

INSERT INTO USERS (NAME,BIRTHDAY)
VALUES ('David', '1998-03-27');

INSERT INTO USERS (NAME,BIRTHDAY)
VALUES ('Kim', '2001-11-15');